# Uncomment the next line to define a global platform for your project
#  platform :ios, '8.1'

target 'formiktest' do
  # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
   pod 'TwilioVoice', '~> 2.0.0'
   pod 'TwilioVideo', '~>2.10.0'

  # Pods for formiktest

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'

  target 'formiktestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'TwilioVoice', '~> 2.0.0'
    pod 'TwilioVideo', '~>2.10.0'

  end

end

target 'formiktest-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for formiktest-tvOS

  target 'formiktest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
