# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'formiktest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for formiktest

  target 'formiktest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'formiktestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'formiktest-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for formiktest-tvOS

  target 'formiktest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
